/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenRouteImport } from './routes/gen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsLangRouteImport } from './routes/words.$lang'

const GenRoute = GenRouteImport.update({
  id: '/gen',
  path: '/gen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsLangRoute = WordsLangRouteImport.update({
  id: '/words/$lang',
  path: '/words/$lang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gen': typeof GenRoute
  '/words/$lang': typeof WordsLangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gen': typeof GenRoute
  '/words/$lang': typeof WordsLangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gen': typeof GenRoute
  '/words/$lang': typeof WordsLangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gen' | '/words/$lang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gen' | '/words/$lang'
  id: '__root__' | '/' | '/gen' | '/words/$lang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenRoute: typeof GenRoute
  WordsLangRoute: typeof WordsLangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gen': {
      id: '/gen'
      path: '/gen'
      fullPath: '/gen'
      preLoaderRoute: typeof GenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$lang': {
      id: '/words/$lang'
      path: '/words/$lang'
      fullPath: '/words/$lang'
      preLoaderRoute: typeof WordsLangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenRoute: GenRoute,
  WordsLangRoute: WordsLangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
